basePath: /api/v1
definitions:
  model.User:
    properties:
      create_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_visible:
        type: boolean
      name:
        type: string
      password:
        type: string
      role_id:
        type: string
      sername:
        type: string
      updated_at:
        type: string
      username:
        type: string
    required:
    - email
    - name
    - password
    - role_id
    - sername
    - username
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Service d'authentification.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: CMagic Auth
  version: 1.0.0
paths:
  /users:
    get:
      description: Récupère la liste de tous les utilisateurs.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: Récupère tous les utilisateurs
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Crée un nouvel utilisateur avec les détails fournis.
      parameters:
      - description: Détails de l'utilisateur
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
      summary: Crée un nouvel utilisateur
      tags:
      - users
  /users/{id}:
    delete:
      description: Supprime un utilisateur en fonction de son ID.
      parameters:
      - description: ID de l'utilisateur
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Aucun contenu
      summary: Supprime un utilisateur
      tags:
      - users
    get:
      description: Récupère un utilisateur en fonction de son ID.
      parameters:
      - description: ID de l'utilisateur
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Récupère un utilisateur par ID
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Met à jour un utilisateur en fonction de son ID avec les détails
        fournis.
      parameters:
      - description: ID de l'utilisateur
        in: path
        name: id
        required: true
        type: integer
      - description: Détails de l'utilisateur à mettre à jour
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Met à jour un utilisateur
      tags:
      - users
  /users/{id}/assign-role/{role}:
    post:
      description: Assigner un rôle spécifié à un utilisateur en fonction de son ID.
      parameters:
      - description: ID de l'utilisateur
        in: path
        name: id
        required: true
        type: integer
      - description: Rôle à assigner
        in: path
        name: role
        required: true
        type: string
      responses:
        "204":
          description: Aucun contenu
      summary: Assigner un rôle à un utilisateur
      tags:
      - users
  /users/{id}/remove-role/{role}:
    post:
      description: Supprimer un rôle spécifié d'un utilisateur en fonction de son
        ID.
      parameters:
      - description: ID de l'utilisateur
        in: path
        name: id
        required: true
        type: integer
      - description: Rôle à supprimer
        in: path
        name: role
        required: true
        type: string
      responses:
        "204":
          description: Aucun contenu
      summary: Supprimer un rôle d'un utilisateur
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
